name = "cryptonean/wallet_template"
version = "0.0.0"
compiler = "v1.1.9"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken template with wallet connetor "

[repository]
user = "cryptonean"
project = "aiken_project_template"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"

